routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', 'AudacityController@index');

Route::get('/img', 'AudacityController@carga_galeria');
Route::post('/galeriapostion', 'GaleriaController@position');


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('user', 'UserController', ['except' => ['show']]);
    Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

Route::post('/recorteimage','GaleriaController@recorte_image');
Route::resource('descripcion', 'DescripcionController');
Route::resource('inicio', 'InicioController');
Route::resource('caracteristicas', 'CaracteristicasController');
Route::resource('galeria','GaleriaController');
Route::resource('departamentos','DepartamentosController');
Route::resource('estado','EstadoController');
Route::post('departamentos/imagen/planos/store', 'DepartamentosController@planostore' )->name('departamentos.store.planos');
Route::post('departamentos/imagen/planos/imagen', 'DepartamentosController@planosimage' )->name('departamentos.imagen.planos');
Route::post('departamentos/imagen/planos/delete/imagen', 'DepartamentosController@planosdeleteimagen')->name('departamentos.imagen.delete.planos');
Route::get('departamentos/data/tipo','AudacityController@carga_tipo');
Route::post('asesorate/confirmacion','EmailController@envia_email');
Route::resource('transparencia','TransparenciaController');
Route::post('inicio/imagen', 'InicioController@iamgen')->name('inicio.imagen');
Route::post('caracteristicas/imagen', 'CaracteristicasController@imagen')->name('caracteristicas.imagen');
Route::post('galeria/imagen','GaleriaController@imagen')->name('galeria.imagen');
Route::post('departamentos/imagen','DepartamentosController@imagen')->name('departamentos.imagen');

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth
    
@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-morado" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand " href="{{ route('home') }}">
            <img src="{{ asset('argon') }}/img/brand/logo.png" class="navbar-brand-img" alt="...">
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Bienvenido!') }}</h6>
                    </div>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{ asset('argon') }}/img/brand/blue.png">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>

            <h6 class="navbar-heading text-muted">Administrable</h6>

            <ul class="navbar-nav mb-md-3">

                <li class="nav-item">
                    <a class="nav-link active" href="#navbar-examples" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-examples">
                        <i class="fab fa-laravel" style="color: #f4645f;"></i>
                        <span class="nav-link-text" style="color: #f4645f;">{{ __('Laravel Examples') }}</span>
                    </a>

                    <div class="collapse show" id="navbar-examples">
                        <ul class="nav nav-sm flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('profile.edit') }}">
                                    {{ __('User profile') }}
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('user.index') }}">
                                    {{ __('User Management') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="javascript:void(0)" onclick="sidebar(this)" ruta='/inicio'>
                        <i class="fa fa-home text-green"></i> {{ __('Inicio') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)" onclick="sidebar(this)" ruta='/descripcion'>
                        <i class="fa fa-info-circle text-green"></i> {{ __('Descripción') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)" onclick="sidebar(this)" ruta='/caracteristicas'>
                        <i class="fa fa-list text-green"></i> {{ __('Caracteristicas') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)" onclick="sidebar(this)" ruta='/galeria'>
                        <i class="fa fa-image text-green"></i> {{ __('Galería') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)" onclick="sidebar(this)" ruta='/departamentos'>
                        <i class="ni ni-building text-green"></i> {{ __('Departamentos') }}
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)" onclick="sidebar(this)" ruta='/estado'>
                        <i class="fa fa-info-circle text-green"></i> {{ __('Estado') }}
                    </a>
                </li>

            </ul>

            <hr class="my-3">

            <h6 class="navbar-heading text-muted">Información</h6>

            <ul class="navbar-nav mb-md-3">
                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)" onclick="sidebar(this)" ruta='/transparencia'>
                        <i class="fa fa-info-circle text-green" ></i> {{ __('Transparencia Senda') }}
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>